import { NextResponse } from "next/server";
import dbConnect from "@/lib/dbConnect";
import Product from "@/models/product";

export async function GET() {
    try {
        await dbConnect();
        const products = await Product.find({}).sort({ createdAt: -1 });
        return NextResponse.json({
            success: true,
            data: products,
            count: products.length,
        });
    } catch (err: any) {
        console.error("GET /api/products ERROR:", err);
        return NextResponse.json(
            { success: false, error: err.message || "Server error" },
            { status: 500 }
        );
    }
}

export async function POST(req: Request) {
    try {
        await dbConnect();
        const body = await req.json();

        // Prevent duplicate key (_id should be auto-generated by MongoDB)
        if (body._id) {
            delete body._id;
        }

        // Ensure image path is relative (not C:\... path)
        if (body.image && body.image.includes("\\")) {
            body.image = body.image.split("public")[1] || body.image;
            body.image = body.image.replace(/\\/g, "/");
        }

        const product = await Product.create(body);
        return NextResponse.json({ success: true, data: product }, { status: 201 });
    } catch (err: any) {
        console.error("POST /api/products ERROR:", err);
        return NextResponse.json(
            { success: false, error: err.message || "Create failed" },
            { status: 400 }
        );
    }
}
